### ISSUE TITLE
Skipping columns when from start some rows are empty (not all)

### ISSUE THREAD

**Issue by KMastalerz** [MarkPflug/Sylvan.Data.Excel#79]
It happens on = `excelDataReader.Initialize();` which finally leads to excpetion `"Specified argument was out of the range of valid values. (Parameter 'names')"` on `var dataReader = excelDataReader.Select(NeededHeaders());`

It stops on NumberOfRecords (column in file - Number of records created/updated/checked) as it's empty for longer period of rows?

Excample file on email. 

**Extract Class:**
```
        private List<T>? SylvanReader<T>()
        {
            try
            {
                var schema = Sylvan.Data.Schema.Parse(JoinHeaders());
                var options = new SylExcel.ExcelDataReaderOptions { Schema = new SylExcel.ExcelSchema(true, schema), GetErrorAsNull = true };
                //collect data
                using (SylExcel.ExcelDataReader excelDataReader = SylExcel.ExcelDataReader.Create(filepath, options))
                {
                    //loop to locate needed sheet from passed setup - not used in this excample
                    if (!string.IsNullOrWhiteSpace(columninfo.SheetName))
                    {
                        while (excelDataReader.WorksheetName != columninfo.SheetName)
                        {
                            excelDataReader.NextResult();

                            if (excelDataReader.WorksheetName == null)
                            {
                                //throw exception, that sheet was not located
                                throw new Exception("didnt find the sheet");
                            }
                        }
                    }

                    //loop to find headers, this will allow to skip unwanted rows, such as comments, empty lines - not used in this excample
                    for (int i = 0; i < columninfo.StartRow; i++)
                    {
                        excelDataReader.Read();
                    }

                    excelDataReader.Initialize();

                    AllRecords = excelDataReader.RowCount;

                    var dataReader = excelDataReader.Select(NeededHeaders());

                    var binderOptions = new DataBinderOptions
                    {
                        InferColumnTypeFromMember = true,
                        BindingMode = DataBindingMode.Any
                    };
                    DataBinder.Create<T>(dataReader, binderOptions);

                    List<T> extracts = dataReader.GetList<T>().ToList();

                    ExtractedRecords = extracts.Count;

                    return extracts;
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
```
JoinHeaders() returns : "TypeOfRequest,IsMass,OutOfScope,OperatingUnit,Country,Other,AccountNumber,RequestID,RequestSystem,RequestorName,RequestorEmail,CompletedBy,DateOfArrival,DateOfCompletion,NumberOfRecords,Comment,RootCause,Priority"
NeededHeaders() returns: 
![image](https://user-images.githubusercontent.com/87186377/183598071-4d8b4624-5b8c-4fa5-bb7a-4f591e6c09f0.png)
![image](https://user-images.githubusercontent.com/87186377/183598090-3e4b316b-c4ae-405b-8d5b-700866af96d4.png)

**Comment by KMastalerz** [comment]
After i addded dummy value to priority it does read all columns, but it seems that binder cannot bind empty cell to int? property. (Ordinal 14)

**Comment by MarkPflug** [comment]
I can't reproduce your issue. This minimal C# 10 application demonstrates binding that column to a nullable int works just fine:

```
using Sylvan.Data;
using Sylvan.Data.Excel;

var reader = ExcelDataReader.Create("Mailbox KPI Template up to 30.06.2022.xlsx");
var binderOpts = 
    new DataBinderOptions { 
        BindingMode = DataBindingMode.AllProperties, 
        InferColumnTypeFromMember = true 
    };

var binder = DataBinder.Create<BindTestClass>(reader, binderOpts);

while (reader.Read())
{
    var item = new BindTestClass();
    binder.Bind(reader, item);
    Console.WriteLine(item.NumberOfRecordsCreatedUpdatedChecked?.ToString() ?? "N/A");
}

class BindTestClass
{
    public int? NumberOfRecordsCreatedUpdatedChecked { get; set; }
}
```

**Comment by KMastalerz** [comment]
[Reader.zip](https://github.com/MarkPflug/Sylvan.Data.Excel/files/9292897/Reader.zip)
Here you go, 
Additionaly, In my project i am currently using Sylvan.Data 0.2.2, i can see in newer 0.2.3 the `Create()` function is changed. This means i would not be able to change it, my entire code for well quite large amount of files depends on generic function. As well as extension i build to accomodate that in GetList(). Could you create `CreateGeneric()` for excample without ` where T : class`. I cannot create my won extension for it as : `CompiledBinderCache` is sealed I assume.

**Comment by MarkPflug** [comment]
I think I see the issue now. The way you are using `ExcelSchema` isn't quite what I'd intended, and my documentation is lacking, so my fault. It looks like you are trying to use the schema to attach explicit header names, and ignore the header that are in the file.

You can implement your own schema provider to handle this:

```
sealed class SimpleSchema : IExcelSchemaProvider
    {
        bool hasHeaders;
        string[] names;

        public SimpleSchema(bool hasHeaders, string[] names)
        {
            this.hasHeaders = hasHeaders;
            this.names = names;
        }

        class SimpleCol : DbColumn
        {
            public SimpleCol(string name)
            {
                this.ColumnName = name;
                this.DataType = typeof(string);
            }
        }

        public DbColumn? GetColumn(string sheetName, string? name, int ordinal)
        {
            if(ordinal < this.names.Length)
            {
                return new SimpleCol(names[ordinal]);
            }
            return null;
        }

        public bool HasHeaders(string sheetName)
        {
            return this.hasHeaders;
        }
    }
```

Then replace your usage of ExcelSchema with SimpleSchema and it should work. I suspect this might be the same issue you reported in the other issue I closed this morning.

Upgrading to 0.2.3 should be relatively painless, you just need to add the type constraint `where T : class, new()` to your generic methods:

```

public List<T>? SylvanReader<T>()
            where T: class, new()
        {
```

```
public static IEnumerable<T> GetList<T>(this DbDataReader reader)
            where T : class, new()
        {
            var binder = DataBinder.Create<T>(reader);
            while (reader.Read())
            {
                var item = new T();
                try
                {
                    binder.Bind(reader, item);
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
                yield return item;
            }
        }
```

**Comment by KMastalerz** [comment]
Yes, you are right about how I use it, I'll test each solution tomorrow but by viewing them i think they might actually work. Although i didn't know ExcelSchema accepts arrays. I Assumed only string with comma delimiters are allowed.

**Comment by KMastalerz** [comment]
Ok i remembered why i started to use it like above. 

My initial issue was incorrect mapping of all columns in `Schema.Parse()`. As it's only accepts comma delimites string, and I do have cases where original columns contain special characters including comma. So i stopped using the names and started passing the names of class properties ill map, with the rest beeing named by their ordinal id. This results in string for excample: "0,Column1,2,3,4,Column5,6". Then after the  `excelDataReader.Initialize();` i want to narrow down the columns to those i actually needed so i extract as `var dataReader = excelDataReader.Select(NeededHeaders());` where `NeededHeaders()` will return `{"Column1","Column5","Column6"}`. I could rework the code to pass actuall headers, as they are known to me from beggining but i think of 2 functionalities, that could prove ok here. 

- Allow to pass string array to `Schema.Parse()` so i do not need to watch for comma delimited names. 
- Provide some boolean function to check if all names are found on file (it's structure is as provided) -> this will provide neat error handlers if someone select wrong file for excample. 

To the point, unfortunately the simple schema, does not solve the issue, im still getting argument out of rang exception after initialization and selecting needed columns.

**Comment by MarkPflug** [comment]
I sent you a working sample targeting the worksheet you mailed me. I've made two changes/fixes to the library to support this, so you'll need to update to 0.2.3.

1) I added the ability to call GetBoolean on string values that aren't "true"/"false", by setting the `TrueString` property on the ExcelDataReaderOptions. This behaves exactly like it does in Sylvan.Data.Csv. This allows your "Yes"/"No" columns to be bound to boolean properties by the databinder, which wouldn't have worked before.

2) I fixed an issue where there are trailing rows in the file that *appear* to be empty, but actually held an empty string value. This was a peculiarity of the file you sent, which I'd never seen before. The last row referenced an empty shared string which was causing a subsequent failure.

Note that the revised code doesn't use the "Sylvan.Data.Schema" type at all. That type was essentially just used as a serialization helper. I replaced it with the `SimpleSchema` which implements the `IExcelSchemaProvider` directly, and I think will be easier for how you use the library.

**Comment by KMastalerz** [comment]
This issue still occurs, 

In my code there is a part below, the columns count is changed after `excelDataReader.Initialize();` i need above as some tables start lower than row 1, where 1 is non empty, as well as looping thru sheets. This was actually implemented after one of your suggestions :) 

```
                    //loop to locate needed sheet from passed setup
                    if (!string.IsNullOrWhiteSpace(columninfo.SheetName))
                    {
                        while (excelDataReader.WorksheetName != columninfo.SheetName)
                        {
                            excelDataReader.NextResult();

                            if (excelDataReader.WorksheetName == null)
                            {
                                //throw exception, that sheet was not located
                                throw new Exception("didnt find the sheet");
                            }
                        }
                    }

                    //loop to find headers, this will allow to skip unwanted rows, such as comments, empty lines
                    for (int i = 0; i < columninfo.StartRow; i++)
                    {
                        excelDataReader.Read();
                    }

                    excelDataReader.Initialize();
```

**Comment by MarkPflug** [comment]
I'm not sure what issue you're seeing now. I sent you working code. I've modified it locally to work against a file that starts on row 4, and it still works after calling Initialize. If you can still reproduce the issue with the latest versions of the libraries then you can open a new issue.

**Comment by KMastalerz** [comment]
It's working fine, I forgot to change SimpleSchema... Just rechecked the upload.
